### ISSUE TITLE
Wardrobe Support

### ISSUE THREAD

**Issue by Ravendwyr** [Jaliborc/ItemSearch-1.3#4]
Wardrobe support appears to be out of date, at least with the current version on Classic servers. The `Wardrobe` object is now a local variable in the file and I'm not sure if it's exposed anywhere.

**Comment by Jaliborc** [comment]
If, like you say, it's not available anywhere on the global namespace, then there's actually nothing I can do to fix it either...

**Comment by Jaliborc** [comment]
Where is the official classic build hosted btw?

**Comment by Ravendwyr** [comment]
I've been using [this one](https://www.curseforge.com/wow/addons/wardrobe).

However, having done some actual digging around I'm pretty sure it's not an official release; more like someone using the same name as [Wardrobe-AL](https://www.curseforge.com/wow/addons/wardrobe-al).

**Comment by Jaliborc** [comment]
I think it's a fan update. There is no official Wardrobe for wow classic as far as I klnow
