### ISSUE TITLE
Something about Mythic Keystones doesn't work

### ISSUE THREAD

**Issue by buddyp450** [Jaliborc/ItemSearch-1.3#5]
I'm not sure why but everything returns true for `Matches` for just the search string `ms` as well. Am currently investigating but haven't touched LUA in a long time and I'm not even sure how to run the test suite.

**Comment by buddyp450** [comment]
Suspecting it was similar to the situations that you had tests for it does indeed look like Mythics have their own API:
https://www.townlong-yak.com/framexml/live/Blizzard_APIDocumentation#C_MythicPlus

**Comment by Jaliborc** [comment]
turns out keystone and pet item links are broken. it should not be possible to search for both by name.
